/************************************************SCRIPT DE LA BDD ***************************/


USE 
MASTER
GO

CREATE DATABASE
RED_LABORAL
GO

USE RED_LABORAL
GO

/**********************CREACION DE TABLAS************/

CREATE TABLE DISTRITO
(
	ID_DISTRITO INT IDENTITY,
	NOMBRE_DISTRITO VARCHAR(100)NOT NULL,
	NOMBRE_PROVINCIA VARCHAR(100)NOT NULL,
	NOMBRE_DEPARTAMENTO VARCHAR(100)NOT NULL,
	ESTADO CHAR(1) NOT NULL
)
GO
ALTER TABLE DISTRITO ADD CONSTRAINT PKDISTRITO PRIMARY KEY (ID_DISTRITO)
GO

CREATE TABLE CARRERA
(
	ID_CARRERA INT IDENTITY,
	NOMBRE_CARRERA VARCHAR(100)NOT NULL,
	RUBRO VARCHAR(100)NOT NULL,
	ESTADO CHAR(1)NOT NULL
)
GO
ALTER TABLE CARRERA ADD CONSTRAINT PKCARRERA PRIMARY KEY (ID_CARRERA)
GO

CREATE TABLE INSTITUCION
(
	ID_INSTITUCION INT IDENTITY,
	NOMBRE_INSTITUCION VARCHAR(100)NOT NULL,
	ESTADO CHAR(1)NOT NULL
)
GO
ALTER TABLE INSTITUCION ADD CONSTRAINT PKINSTITUCION PRIMARY KEY (ID_INSTITUCION)
GO

CREATE TABLE PUESTO 
(
	ID_PUESTO INT IDENTITY,
	NOMBRE_PUESTO VARCHAR(100)NOT NULL,
	RUBRO VARCHAR(100)NOT NULL,
	ESTADO CHAR(1)NOT NULL

)
GO
ALTER TABLE PUESTO ADD CONSTRAINT PKPUESTO PRIMARY KEY (ID_PUESTO)
GO

CREATE TABLE EMPRESA
(
	RUC CHAR(11)NOT NULL,
	RAZON_SOCIAL VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	ID_DISTRITO INT NOT NULL,
	EMAIL VARCHAR(70)NULL,
	PASSWORD1 VARCHAR(10) NOT NULL,
	ESTADO CHAR(1)NOT NULL
)
GO
ALTER TABLE EMPRESA ADD CONSTRAINT PKEMPRESA PRIMARY KEY (RUC)
GO



CREATE TABLE PERSONA
(
	DNI CHAR (8)  NOT NULL,
	NOMBRES VARCHAR(60)NULL,
	APELLIDO_PATERNO VARCHAR(50)NULL,
	APELLIDO_MATERNO VARCHAR(50)NULL,	
	TELEFONO VARCHAR(7)NULL,
	CELULAR VARCHAR(9)NULL,
	EMAIL VARCHAR(70)NULL,
	FECHA_NACIMIENTO DATETIME NULL,
	DIRECCION VARCHAR(200)NULL,
	ID_DISTRITO INT NULL,
	PASSWORD1 VARCHAR(10) NOT NULL,		
	ESTADO CHAR(1) NOT NULL	
)
ALTER TABLE PERSONA ADD CONSTRAINT PKPERSONA PRIMARY KEY (DNI)
GO

CREATE TABLE PERSONA_CARRERA 
(
	DNI CHAR (8)  NOT NULL,
	ID_CARRERA INT NOT NULL,
	ID_INSTITUCION INT,
	PROMEDIO INT,
	PUESTO_FINAL INT,
	F_INICIO DATE,
	F_FIN DATE,
	ESTADO CHAR(1) NOT NULL	
)
GO
ALTER TABLE PERSONA_CARRERA ADD CONSTRAINT PKPERSONA_CARRERA PRIMARY KEY (DNI,ID_CARRERA)
GO

CREATE TABLE TRABAJO
(
	ID_TRABAJO INT IDENTITY,
	DNI CHAR (8)  NOT NULL,
	RUC CHAR(11) NOT NULL,
	ID_PUESTO INT NOT NULL,
	FECHA_INICIO DATETIME,
	FECHA_FIN DATETIME,
	ESTADO CHAR(1)NOT NULL
)
GO
ALTER TABLE TRABAJO ADD CONSTRAINT PKTRABAJO PRIMARY KEY (ID_TRABAJO)
GO


CREATE TABLE H_BLANDA
(
	ID_H_BLANDA INT IDENTITY,
	NOMBRE_HABILIDAD VARCHAR(100)NOT NULL,
	RUBRO VARCHAR (100)NOT NULL,
	ESTADO CHAR(1)NOT NULL
)
GO
ALTER TABLE H_BLANDA ADD CONSTRAINT PKH_BLANDA PRIMARY KEY (ID_H_BLANDA)
GO

CREATE TABLE H_DURA
(
	ID_H_DURA INT IDENTITY,
	NOMBRE_HABILIDAD VARCHAR(100)NOT NULL,
	RUBRO VARCHAR (100)NOT NULL,
	ESTADO CHAR(1)NOT NULL
)
GO
ALTER TABLE H_DURA ADD CONSTRAINT PKH_DURA PRIMARY KEY (ID_H_DURA)
GO


CREATE TABLE PUNTUACION_BLANDA
(
	ID_TRABAJO INT NOT NULL,
	ID_H_BLANDA INT NOT NULL,
	PUNTOS INT,
	ESTADO CHAR(1)
)
GO
ALTER TABLE PUNTUACION_BLANDA ADD CONSTRAINT PKPUNTUACION_BLANDA PRIMARY KEY (ID_TRABAJO, ID_H_BLANDA)
GO

CREATE TABLE PUNTUACION_DURA
(
	ID_TRABAJO INT NOT NULL,
	ID_H_DURA INT NOT NULL,
	PUNTOS INT,
	ESTADO CHAR(1)
)
GO
ALTER TABLE PUNTUACION_DURA ADD CONSTRAINT PKPUNTUACION_DURA PRIMARY KEY (ID_TRABAJO, ID_H_DURA)
GO



/***************************************************************************************************************************/
/******************************************************LLAVES FORANEAS******************************************************/
/***************************************************************************************************************************/


ALTER TABLE PERSONA ADD CONSTRAINT  FKPERSONA FOREIGN KEY (ID_DISTRITO)
REFERENCES DISTRITO
GO

ALTER TABLE EMPRESA ADD CONSTRAINT  FKEMPRESA FOREIGN KEY (ID_DISTRITO)
REFERENCES DISTRITO
GO

ALTER TABLE PERSONA_CARRERA ADD CONSTRAINT FKPERSONA_CARRERA FOREIGN KEY (DNI)
REFERENCES PERSONA
GO

ALTER TABLE PERSONA_CARRERA ADD CONSTRAINT FKPERSONA_CARRERA1 FOREIGN KEY (ID_CARRERA)
REFERENCES CARRERA
GO

ALTER TABLE PERSONA_CARRERA ADD CONSTRAINT FKPERSONA_CARRERA2 FOREIGN KEY (ID_INSTITUCION)
REFERENCES INSTITUCION
GO

ALTER TABLE TRABAJO ADD CONSTRAINT  FKTRABAJO FOREIGN KEY (ID_PUESTO)
REFERENCES PUESTO
GO

ALTER TABLE TRABAJO ADD CONSTRAINT  FKTRABAJO1 FOREIGN KEY (DNI)
REFERENCES PERSONA
GO

ALTER TABLE TRABAJO ADD CONSTRAINT  FKTRABAJO2 FOREIGN KEY (RUC)
REFERENCES EMPRESA
GO

ALTER TABLE PUNTUACION_BLANDA ADD CONSTRAINT FKPUNTUACION_BLANDA1 FOREIGN KEY (ID_TRABAJO)
REFERENCES TRABAJO
GO

ALTER TABLE PUNTUACION_BLANDA ADD CONSTRAINT FKPUNTUACION_BLANDA2 FOREIGN KEY (ID_H_BLANDA)
REFERENCES H_BLANDA
GO

ALTER TABLE PUNTUACION_DURA ADD CONSTRAINT FKPUNTUACION_DURA1 FOREIGN KEY (ID_TRABAJO)
REFERENCES TRABAJO
GO

ALTER TABLE PUNTUACION_DURA ADD CONSTRAINT FKPUNTUACION_DURA2 FOREIGN KEY (ID_H_DURA)
REFERENCES H_DURA
GO




 