USE [RED_LABORAL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOLSA](
	[DNI] [char] NOT NULL,
	[RUC] [char](11) NOT NULL,
	[FECHA_APLICACION] [datetime] NOT NULL
 CONSTRAINT [PKBOLSA] PRIMARY KEY CLUSTERED 
(
	[DNI],[RUC]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


