USE [RED_LABORAL]
GO
/****** Object:  StoredProcedure [dbo].[SP_INGRESAR_OFERTA_LABORAL]    Script Date: 7/11/2018 9:56:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INGRESAR_OFERTA_LABORAL]
(
	   @XRUC VARCHAR(11)
      ,@XTITULO VARCHAR(60)
      ,@XLUGAR VARCHAR(60)
      ,@XID_PUESTO INT
      ,@XDESCRIP VARCHAR(400)
      ,@XFUNCIONES VARCHAR(400)
      ,@XID_JORNADA INT
      ,@XID_TIPOCONTRATO INT
      ,@XREQUISITOS VARCHAR(400)
      ,@XCOMPETENCIAS VARCHAR(400)
      ,@XESTADO CHAR(1)
	  ,@XLASTID INT OUTPUT
)
AS
INSERT INTO [dbo].[OFERTA_LABORAL] ([RUC]
      ,[TITULO]
      ,[LUGAR]
      ,[ID_PUESTO]
      ,[DESCRIP]
      ,[FUNCIONES]
      ,[ID_JORNADA]
      ,[ID_TIPOCONTRATO]
      ,[REQUISITOS]
      ,[COMPETENCIAS]
      ,[ESTADO])

VALUES (@XRUC
      ,@XTITULO
      ,@XLUGAR
      ,@XID_PUESTO
      ,@XDESCRIP
      ,@XFUNCIONES
      ,@XID_JORNADA
      ,@XID_TIPOCONTRATO
      ,@XREQUISITOS
      ,@XCOMPETENCIAS
      ,@XESTADO)

SELECT @XLASTID = SCOPE_IDENTITY()
GO

USE [RED_LABORAL]
GO
/****** Object:  StoredProcedure [dbo].[SP_CONSULTAR_OFERTA_LABORAL]    Script Date: 7/11/2018 9:56:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


---CONSULTAR---
CREATE PROCEDURE [dbo].[SP_CONSULTAR_OFERTA_LABORAL]
	@XID_OFERTA INT
AS
SELECT [ID_OFERTA]
      ,[RUC]
      ,[TITULO]
      ,[LUGAR]
      ,[ID_PUESTO]
      ,[DESCRIP]
      ,[FUNCIONES]
      ,[ID_JORNADA]
      ,[ID_TIPOCONTRATO]
      ,[REQUISITOS]
      ,[COMPETENCIAS]
      ,[ESTADO]
  FROM [RED_LABORAL].[dbo].[OFERTA_LABORAL]
WHERE [ID_OFERTA]= @XID_OFERTA
GO